### ISSUE TITLE
Develop a logo for Notary

### ISSUE THREAD

**Issue by caniszczyk** [theupdateframework/notary#1189]
Since Notary has been formally invited for a project proposal to CNCF (https://github.com/cncf/toc/pull/38) I figure we would help you out a bit with a logo while that process happens in parallel.

I've spoken with @endophage about this already and will kick around some ideas.

**Comment by endophage** [comment]
@ecordell @HuKeping I hadn't gotten around to emailing you the good news yet, as note above, we passed the first hurdle in the CNCF submission process!

I sent @caniszczyk a few seal/stamp based inspirations for logos. If any of the other maintainers are interested in being involved in the logo design, I'll add you to the email chain. Otherwise I'll share whatever shortlist we come up with.

**Comment by HuKeping** [comment]
Cooooooooooooooooooooooooooooooool!

**Comment by caniszczyk** [comment]
@endophage I reached out to LF Design, they suggested to work with 99designs first to generate logo ideas and then they can refine it if necessary.

Here's a first poll with some ideas: https://99designs.com/contests/poll/ks4pfg

Please rate them :)

**Comment by HuKeping** [comment]
I think `#33 by hantoko` is a little complicated.  I prefer a simple one.

**Comment by caniszczyk** [comment]
Here's another poll to help iterate on designs cc: @endophage et al

**Comment by endophage** [comment]
@caniszczyk I think you omitted the link by accident?

**Comment by caniszczyk** [comment]
@endophage ooops, sorry, should be here: https://99designs.com/contests/poll/uzjnyl

Please reach out to all the Notary devs and have them vote so we can close this out :)

**Comment by endophage** [comment]
Notary logo can be found in github.com/theupdateframework/artwork
