### ISSUE TITLE
Can we have 2 Notary server connected to one Notary Signer ?

### ISSUE THREAD

**Issue by Rahul-github** [theupdateframework/notary#1273]
Greetings All:

we are running Docker Notary in AWS ECS, managing 2 services one for server and other for the signer. we would like to scale Notary Server.

Will it be possible to have 2 servers and one Signer connecting(using Postgres DB)?

Thank you in advance!

**Comment by HuKeping** [comment]
Thank you for try notary on AWS @Rahul-github 

> Will it be possible to have 2 servers and one Signer connecting(using Postgres DB)?

Yes.

**Comment by Rahul-github** [comment]
:) 
You mean it is possible with ECS in AWS, can you please help me what thing I have to include because I heard that we need HTTP 2.0 which AWS doesn't support

**Comment by Rahul-github** [comment]
can anyone please help on this issue?

**Comment by Rahul-github** [comment]
@HuKeping 
If I'm implementing reverse-proxy in front of notary server and starting the second node of notary server, can I connect to the same Database or do I need a different database for the different server?

**Comment by cyc115** [comment]
My understanding is that you can connect to the same DB.

**Comment by cyli** [comment]
@cyc115 Is definitely correct - you can have multiple servers connecting to the same DB, and they can all connect to a single signer or possibly multiple signers scaled behind a load balancer.  Please see https://github.com/theupdateframework/notary/blob/master/docs/running_a_service.md#high-availability.

I am going to close this issue because @cyc115 has already answered, but please feel free to re-open if you feel that it has not been addressed!
