### ISSUE TITLE
How to fetch images from Docker hub if you enabled Content Trust

### ISSUE THREAD

**Issue by Rahul-github** [theupdateframework/notary#1275]
We have enabled content Trust and unable to fetch images from Docker hub
[sahotay@myserver-notary~]$ env | grep -i docker
DOCKER_CONTENT_TRUST=1
DOCKER_CONTENT_TRUST_SERVER=https://notaryserver:4443

Here is the error we are seeing
sahotay@myserver-notary~]$ docker pull nginx
Using default tag: latest
Error: remote trust data does not exist for docker.io/library/nginx: notaryserver:4443 does not have trust data for docker.io/library/nginx

However, i can disable content trust and build or pull the image but if I have to do this in the pipeline(Jenkins or other tools) how to do this?

**Comment by Rahul-github** [comment]
Can anyone help me here, please?

**Comment by HuKeping** [comment]
As per the error message, it's because there is no trust data for `docker.io/library/nginx` in your notary service . 

There is at least two solutions,
1. change your notary server to the one docker provided(i'm not sure if there is one)
2. pull the image from your own registry, if so, you can first push the image to your own registry and notary will generate the trust data for it.

**Comment by reasonerjt** [comment]
I think this is a limitation due to the design of docker content trust, one docker client may pull images from different registries, but there's only one setting for `DOCKER_CONTENT_TRUST_SERVER`.

But yes one can argue it's working as expected.

**Comment by ecordell** [comment]
I believe this is purely a docker client (ux) issue and not a notary issue. I'm going to close this but feel free to comment if it seems like something that can be reasonably addressed in notary, and we can re-open.
