### ISSUE TITLE
Contributing guidelines says two LGTMs

### ISSUE THREAD

**Issue by eiais** [theupdateframework/notary#1359]
Is that no longer the case?

**Comment by cyli** [comment]
We generally enforce this for larger code changes - minor doc fixes, ci fixes, dependency bumps, etc we usually let go with 1, since we don’t have a lot of reviewers.

You are correct in that we should probably be clearer about the guidelines as to what counts as minor.

**Comment by ecordell** [comment]
I think it would be fine to merge minor fixes with 1 LGTM. We can revisit if we find the definition of "minor" stretching too much (but I'm sure it will be fine).

**Comment by endophage** [comment]
I'd rather we leave the maintainer rules as is and simply recognize that we're pragmatic individuals and make reasonable decisions. "Minor" is subjective, especially once code is involved. Rather than codifying 1 LGTM for "minor" fixes in the rules and having the possibility it creeps, my vote is to leave it as 2 LGTMs for everything and recognize/explicitly document in the PR the special circumstances when they occur.

**Comment by HuKeping** [comment]
If code involved , I'd vote for 2 LGTM.  It might be fine if the change was just a typo or something really small,  but a misleading docs is even worse than no docs.
